import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import runtimeCatalog from "../data/recipe-runtime-catalog.json" with { type: "json" };
import releaseAudit from "../data/recipe-release-audit.json" with { type: "json" };
import simplePhotoManifest from "../data/simple-recipe-images.json" with { type: "json" };
import {
  buildMobileBootstrap,
  type RuntimeAuditForMobile,
  type RuntimeCatalogForMobile,
  type SimplePhotoManifestForMobile,
} from "../domain/mobile.ts";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const bootstrap = buildMobileBootstrap(
  runtimeCatalog as RuntimeCatalogForMobile,
  releaseAudit as RuntimeAuditForMobile,
  simplePhotoManifest as SimplePhotoManifestForMobile,
);

const jsonPath = resolve(root, "apps/native/assets/mobile-bootstrap.json");
const assetMapPath = resolve(root, "apps/native/src/generated/recipe-assets.ts");
await mkdir(dirname(jsonPath), { recursive: true });
await mkdir(dirname(assetMapPath), { recursive: true });

const assetLines = bootstrap.recipes.map((recipe) => {
  const relativePath = `../../../../public${recipe.photo.path}`;
  return `  ${JSON.stringify(recipe.id)}: require(${JSON.stringify(relativePath)}),`;
});
const assetMap = [
  "/* Generated by scripts/build-mobile-bootstrap.ts. Do not edit by hand. */",
  "/* eslint-disable @typescript-eslint/no-require-imports */",
  "import type { ImageSourcePropType } from \"react-native\";",
  "",
  "export const recipeAssets: Record<string, ImageSourcePropType> = {",
  ...assetLines,
  "};",
  "",
].join("\n");

await Promise.all([
  writeFile(jsonPath, `${JSON.stringify(bootstrap)}\n`, "utf8"),
  writeFile(assetMapPath, assetMap, "utf8"),
]);

process.stdout.write(
  `${JSON.stringify({ schemaVersion: bootstrap.schemaVersion, recipes: bootstrap.recipes.length })}\n`,
);
